### ISSUE TITLE
Regex and replace functions should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-core#62]

**Comment by mimopotato** [comment]
```yaml
key:
  _replace:
    - "a"
    - "b"
```
