### ISSUE TITLE
_fromJson should be implemented

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/funcml-core#68]
```yaml
key:
  _fromJson: |
    {"test": "abc"}
```

```yaml
key:
  test: abc
```
